package:
  format-version: "1.0.0"
  name: "standalone_PHY"
  type: "api"
  status: "beta"
  required: false
  version: "1.0.0"

  dependencies:
    - name: "core"
      type: "package"
      version: "3.13.0"
    - name: "csp"
      type: "package"
      version: "3.18.0"
    - name: "bsp"
      type: "package"
      version: "3.17.0"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "10.3.1"
    - name: "dev_packs"
      type: "package"
      version: "3.17.0"
    - name: "wireless_system_pic32cxbz_wbz"
      type: "package"
      version: "1.3.0"
