package:
  format-version: "1.1.0"
  name: "wireless_15_4_phy_trx"
  type: "api"
  status: "beta"
  required: false
  version: "1.1.0"

  dependencies:
    - name: "core"
      type: "package"
      version: "3.13.1"
    - name: "csp"
      type: "package"
      version: "3.18.4"
    - name: "bsp"
      type: "package"
      version: "3.17.0"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "10.3.1"
    - name: "dev_packs"
      type: "package"
      version: "3.17.0"
